### ISSUE TITLE
Upgrading to Angular 2 Release Candidate

### ISSUE THREAD

**Issue by robisim74** [damienbod/Angular2LocalizationAspNetCore#1]
Hi. I want to ask you if you are interested to upgrade your project to Angular2 rc.01. To solve the problem of the absence of bundles, I adopted the angular-cli, but through gulp solution. Not great, but it works (pending official solutions by Angular Team). I prepared a pr if you want to.

**Comment by damienbod** [comment]
Hi @robisim74 Yes, thanks, I testing angular-cli as well on a different repo first, If this works, I plan to upgrade using this, but requires that I split the UI and API into two separate projects.

Why did you use gulp?, just to copy or a different reason.

Thanks greetings Damien

**Comment by robisim74** [comment]
See [here](https://github.com/robisim74/Angular2LocalizationAspNetCore). 
I did with gulp what makes angular -cli . So you do not change anything .

**Comment by damienbod** [comment]
Looks good, can you create a pull request and use it,

Thanks a million

Greetings Damien

**Comment by robisim74** [comment]
:ok_hand:

**Comment by damienbod** [comment]
I'll update the blog as soon as I can, thanks again, I like your solution. 

Greetings Damien

**Comment by robisim74** [comment]
I am following Angular2 from the beginning ... I'm used to these changes. Thank you, does not happen every day be tweeted from ASP.NET team...

**Comment by damienbod** [comment]
No bundles is a big change for me... Other ASP:NET developers are also fighting with this. Thanks for cleaning up the gulp file, I was meaning to add a clean to it.

Greetings Damien

**Comment by robisim74** [comment]
The open source world is so ... constant changes. We must trust!
